name: Build
on: [push, pull_request]

jobs:
   build:
      runs-on: ${{ matrix.os }}

      strategy:
         matrix:
            os: [macos-latest, ubuntu-latest, windows-latest]

      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@master
           with:
              node-version: 14

         - name: Install dependencies
           run: yarn install

         - name: Build
           run: yarn run build
